import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from datetime import datetime

def generate_session_pdf(session, transcripts, suggestions) -> bytes:
    """Generate a PDF summary for a consultation session and return it as bytes."""

    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm,
    )

    styles  = getSampleStyleSheet()
    content = []

    # Custom styles
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=20,
        textColor=colors.HexColor("#0f172a"),
        alignment=TA_CENTER,
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#64748b"),
        alignment=TA_CENTER,
        spaceAfter=20,
    )
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=16,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#334155"),
        leading=16,
    )
    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#94a3b8"),
        spaceAfter=2,
    )

    # Header
    content.append(Paragraph("MedAssist", title_style))
    content.append(Paragraph("Consultation Report", subtitle_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    content.append(Spacer(1, 12))

    # Session info
    content.append(Paragraph("Session Details", section_style))
    created = datetime.fromisoformat(str(session.created_at)).strftime("%B %d, %Y at %I:%M %p")
    info_data = [
        ["Session Title", session.title],
        ["Session ID",    str(session.id)],
        ["Date",          created],
    ]
    info_table = Table(info_data, colWidths=[4*cm, 13*cm])
    info_table.setStyle(TableStyle([
        ("FONTSIZE",    (0, 0), (-1, -1), 10),
        ("TEXTCOLOR",  (0, 0), (0, -1), colors.HexColor("#64748b")),
        ("TEXTCOLOR",  (1, 0), (1, -1), colors.HexColor("#1e293b")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    content.append(info_table)
    content.append(Spacer(1, 12))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))

    # Transcript
    content.append(Paragraph("Transcript", section_style))
    if transcripts:
        for t in transcripts:
            content.append(Paragraph(t.text, body_style))
            content.append(Spacer(1, 6))
    else:
        content.append(Paragraph("No transcript available.", body_style))

    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))

    # Suggestions
    content.append(Paragraph("AI Suggestions", section_style))

    if suggestions:
        for s in suggestions:
            # Type and status badge
            status_color = {
                "accepted": "#22c55e",
                "rejected": "#ef4444",
                "modified": "#f59e0b",
                "pending":  "#94a3b8",
            }.get(str(s.status.value if hasattr(s.status, 'value') else s.status), "#94a3b8")

            type_label = {
                "diagnosis": "Diagnosis",
                "test":      "Recommended Test",
                "drug":      "Drug / Dosage",
                "red_flag":  "Red Flag",
            }.get(s.type, s.type)

            content.append(Paragraph(
                f'<font color="{status_color}">●</font> <b>{type_label}</b> '
                f'— <font color="#94a3b8">{s.confidence} confidence</font>',
                body_style
            ))
            content.append(Paragraph(s.content, body_style))

            if s.doctor_note:
                content.append(Paragraph(f"Doctor note: {s.doctor_note}", label_style))

            content.append(Spacer(1, 8))
    else:
        content.append(Paragraph("No suggestions generated for this session.", body_style))

    # Footer
    content.append(Spacer(1, 20))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    content.append(Spacer(1, 6))
    content.append(Paragraph(
        "Generated by MedAssist — for clinical reference only. Doctor review required.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
                       textColor=colors.HexColor("#94a3b8"), alignment=TA_CENTER)
    ))

    doc.build(content)
    buffer.seek(0)
    return buffer.read()